SQL> SELECT s.Name, sa.Country, sa.Province, sa.City, sa.Street, sa.House_Number, sat. Address_Type, sci.Phone_Number1, sci.Phone_Number2
  2  FROM Student s
  3  JOIN Student_Address_Type sat
  4  ON s.Student_ID = sat.Student_ID
  5  JOIN Student_Address sa
  6  ON sat.Student_Address_ID = sa.Student_Address_ID
  7  JOIN Student_Contact_Info sci
  8  ON sci.House_Number = sa.House_Number
  9  ORDER BY Name;

NAME                 COUNTRY              PROVINCE             CITY                 STREET               HOUSE_NUMBER ADDRESS_TYPE    PHONE_NUMBER1 PHONE_NUMBER2                                                                                                                                                                                                                                               
-------------------- -------------------- -------------------- -------------------- -------------------- ------------ --------------- ------------- -------------                                                                                                                                                                                                                                               
Aditi Dhakal         Nepal                Province 2           Birgunj              Ghantaghar                   3078 Permanent          9825987059    9841808752                                                                                                                                                                                                                                               
Aditi Dhakal         Nepal                Bagmati              Kathmandu            New Road                     1078 Temporary          9809887666                                                                                                                                                                                                                                                             
Alisha Basnet        Nepal                Gandaki              Gorkha               Khaireni                     6060 Permanent          9813126745    9848819580                                                                                                                                                                                                                                               
Alisha Basnet        Nepal                Bagmati              Kathmandu            Baneshwor                    1075 Temporary          9875675534    9840098585                                                                                                                                                                                                                                               
Ashish Gautam        Nepal                Bagmati              Kathmandu            Asan                         1096 Permanent          9868890665    9841724570                                                                                                                                                                                                                                               
Grisha Giri          Nepal                Bagmati              Kathmandu            Kuleshwor                    1056 Permanent          9823456718    9849644291                                                                                                                                                                                                                                               
Labbi Karmasta       Nepal                Bagmati              Kathmandu            Durbarmarg                   1021 Temporary          9873777779    9818248640                                                                                                                                                                                                                                               
Labbi Karmasta       Nepal                Gandaki              Pokhara              Nayabazar                    4099 Permanent          9843819860    9860848077                                                                                                                                                                                                                                               
Pragati Gautam       Nepal                Bagmati              Kathmandu            Putalisadak                  1093 Permanent          9887653700                                                                                                                                                                                                                                                             
Prince Panjiyar      Nepal                Bagmati              Kathmandu            Thapathali                   1098 Permanent          9851078766                                                                                                                                                                                                                                                             
Rohit Parajuli       Nepal                Bagmati              Kathmandu            Thamel                       1010 Temporary          9808761098    9865077564                                                                                                                                                                                                                                               

NAME                 COUNTRY              PROVINCE             CITY                 STREET               HOUSE_NUMBER ADDRESS_TYPE    PHONE_NUMBER1 PHONE_NUMBER2                                                                                                                                                                                                                                               
-------------------- -------------------- -------------------- -------------------- -------------------- ------------ --------------- ------------- -------------                                                                                                                                                                                                                                               
Rohit Parajuli       Nepal                Province 2           Nawalparasi          Parasi                       5081 Permanent          9841709854                                                                                                                                                                                                                                                             
Rojan Shrestha       Nepal                Bagmati              Kathmandu            Dllibazar                    1021 Permanent          9873777779    9818248640                                                                                                                                                                                                                                               
Roman Bhandari       Nepal                Bagmati              Kathmandu            Tinkune                      1042 Temporary          9808980780                                                                                                                                                                                                                                                             
Roman Bhandari       Nepal                Province 1           Biratnagar           Buspark                      7071 Permanent          9846871009                                                                                                                                                                                                                                                             
Simran Ranjit        Nepal                Bagmati              Kathmandu            Koteshwor                    1089 Permanent          9878900760                                                                                                                                                                                                                                                             
Srijan Adhikari      Nepal                Bagmati              Kathmandu            Balkhu                       1069 Temporary          9800776698    9860033237                                                                                                                                                                                                                                               
Srijan Adhikari      Nepal                Lumbini              Butwal               Buddhanagar                  2020 Permanent          9807610886                                                                                                                                                                                                                                                             

18 rows selected.

SQL> SPOOL OFF;
