SQL> SELECT DISTINCT(Module_Name), Class_ID
  2  FROM Module
  3  GROUP BY Module_Name, Class_ID
  4  HAVING COUNT(Class_ID)=1
  5  ORDER BY Class_ID;

MODULE_NAME          CLASS_ID                                                                                                                                                                                                                                                                                                                                                                                   
-------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                 
3D Modelling         LT01                                                                                                                                                                                                                                                                                                                                                                                       
Database             LT01                                                                                                                                                                                                                                                                                                                                                                                       
Service Marketing    LT02                                                                                                                                                                                                                                                                                                                                                                                       
Accounting           LTO8                                                                                                                                                                                                                                                                                                                                                                                       
Cyber Security Mgmt  SR03                                                                                                                                                                                                                                                                                                                                                                                       
Economics            SR03                                                                                                                                                                                                                                                                                                                                                                                       
Ethical Hacking      TR07                                                                                                                                                                                                                                                                                                                                                                                       
Software Eng         TR12                                                                                                                                                                                                                                                                                                                                                                                       

8 rows selected.

SQL> SPOOL OFF;
