SQL> SELECT s.Name, c.Course_Name, sp.Fees,
  2  CASE sp.Specification_Name WHEN 'Computing' THEN 0.9*sp.Fees
  3  ELSE sp.Fees END "Discounted Fees"
  4  FROM Student s
  5  JOIN Marks m
  6  ON s.Student_ID = m.Student_ID
  7  JOIN Specification sp
  8  ON sp.Specification_ID = m.Specification_ID
  9  JOIN Course c
 10  ON c.Course_ID = m.Course_ID;

NAME                 COURSE_NAME                FEES Discounted Fees                                                                                                                                                                                                                                                                                                                                            
-------------------- -------------------- ---------- ---------------                                                                                                                                                                                                                                                                                                                                            
Alisha Basnet        BBA                      105000          105000                                                                                                                                                                                                                                                                                                                                            
Aditi Dhakal         B.Sc.IT                  120000          120000                                                                                                                                                                                                                                                                                                                                            
Ashish Gautam        BBA                      100000          100000                                                                                                                                                                                                                                                                                                                                            
Grisha Giri          B.Sc.IT                  115000          103500                                                                                                                                                                                                                                                                                                                                            
Labbi Karmasta       B.Sc.IT                  115000          103500                                                                                                                                                                                                                                                                                                                                            
Pragati Gautam       B.Sc.IT                  120000          120000                                                                                                                                                                                                                                                                                                                                            
Prince Panjiyar      MBA                       95000           95000                                                                                                                                                                                                                                                                                                                                            
Roman Bhandari       BBA                      103000          103000                                                                                                                                                                                                                                                                                                                                            
Rohit Parajuli       M.Sc.IT                   90000           90000                                                                                                                                                                                                                                                                                                                                            
Rojan Shrestha       BBA                      103000          103000                                                                                                                                                                                                                                                                                                                                            
Srijan Adhikari      B.Sc.IT                  117000          117000                                                                                                                                                                                                                                                                                                                                            

NAME                 COURSE_NAME                FEES Discounted Fees                                                                                                                                                                                                                                                                                                                                            
-------------------- -------------------- ---------- ---------------                                                                                                                                                                                                                                                                                                                                            
Simran Ranjit        B.Sc.IT                  117000          117000                                                                                                                                                                                                                                                                                                                                            

12 rows selected.

SQL> SPOOL OFF;
